name: Code checks and tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Terraform format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: fmt
          tf_actions_working_dir: "."
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

      - name: Run Terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: init
          tf_actions_working_dir: "./tests"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

      - name: Run Terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: validate
          tf_actions_working_dir: "./tests"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

  shellcheck:
    name: Check Shellscripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          reporter: github-pr-review

