name: Release

on:
  workflow_run:
    workflows:
      - "Code checks and tests"
    branches:
      - master
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@master
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
